### ISSUE TITLE
[1]    41086 segmentation fault  node wx_jump.js

### ISSUE THREAD

**Issue by mylhei** [aOrz/wx_jump_game#1]
[1]    41086 segmentation fault  node wx_jump.js

错误定位在20行，

发现adb拉下的图片不是标准png，从网上找了解决方案没有生效。
`LC_ALL=C sed 's/\r$//'` 并没有生效
最后还是使用了
` shell.exec('adb shell screencap -p /sdcard/1.png');
    shell.exec('adb pull /sdcard/1.png');
    shell.exec('adb shell rm /sdcard/1.png');`

**Comment by aOrz** [comment]
thx
