### ISSUE TITLE
排行榜被屏蔽了？

### ISSUE THREAD

**Issue by lewis617** [aOrz/wx_jump_game#5]
我用这个项目刷了1600多分，刚开始排行榜是第一，但退出游戏重新进入后，变成之前人工玩出的分数了。排行榜被屏蔽了？

**Comment by aOrz** [comment]
是会发生被屏蔽的情况，所以，不要刷太高。。。

**Comment by lewis617** [comment]
我后来刷了一个500多的结果也被屏蔽了，回到了之前的分数（400多）

**Comment by aOrz** [comment]
增加了随机休眠机制
